name = "device-api"
main = "src/main-worker.ts"
compatibility_date = "2024-09-29"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "spaia-images"
preview_bucket_name = "spaia-images"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "e110feeffb8947a8bb236c3727f43034"

[[queues.producers]]
queue = "csv-processing-queue"
binding = "MY_QUEUE"

[[queues.consumers]]
queue = "csv-processing-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "csv-processing-dlq"


# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"





# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"


