name = "device-api"
main = "src/index.ts"
compatibility_date = "2024-09-29"
compatibility_flags = [ "nodejs_compat" ]


# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "spaia-images"
preview_bucket_name = "spaia-images"



# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "ce3066c01533475db98806f6ee39909f"